# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_auto_20171028_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default='', max_length=500)),
                ('correct_answer', models.CharField(default='', max_length=20)),
                ('parent_quiz', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index.Quiz')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
    ]
