# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_auto_20171028_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_scored', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='submissions',
        ),
        migrations.AlterField(
            model_name='course',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='all_students',
            field=models.ManyToManyField(to='index.Student'),
        ),
        migrations.AddField(
            model_name='assignment_submission',
            name='submission_assignment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index.Assignment'),
        ),
        migrations.AddField(
            model_name='assignment_submission',
            name='submission_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index.Student'),
        ),
    ]
